# This is a basic workflow that is manually triggered

name: Test version bump workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  create:
    tags:
      -**

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  bump-version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
      - name: Checkout 
        uses: actions/checkout@v2
        
      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          target-branch: 'master'
