name: Workflow to create a PR for a given tag branch to given destination branch
on: 
  workflow_dispatch:
    inputs:
      tagVersion:
        description: 'Tag Version'     
        required: true
        default: ''
      targetBranch:
        description: 'Target branch'
        required: true
      semanticUpgrade:
        description: 'Npm Upgrade type'
        required: true
        default: 'patch'
jobs:
  bumpVersion:
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        
      - uses: actions/checkout@v2

      - name: get version from package.json file
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
            path: 'package.json'
            prop_path: 'version'
      - run: echo ${{steps.version.outputs.prop}} 

      - name: Create tag branch
        run: git checkout -b tag/${{ github.event.inputs.tagVersion }}
        
      - name: Initialize mandatory git config
        run: |
         git config user.name "GitHub Actions"
         git config user.email noreply@github.com
            
      - name: Update version number
        run: | 
          npm version ${{ github.event.inputs.semanticUpgrade }} -no-git-tag-version --force
          
      - name: Commit package.json file
        id: make-commit
        run: |
          git add package.json
          git commit -m "updated version to ${{ github.event.inputs.semanticUpgrade }}"
          
      - name: Push new branch
        run: |
          git push origin tag/${{ github.event.inputs.tagVersion }}
          echo ${{ toJSON(steps.make-commit-outputs) }}
        
      - name: Create pull request into main
        uses: thomaseizinger/create-pull-request@1.1.0
        with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         head: tag/${{ github.event.inputs.tagVersion }}
         base: ${{ github.event.inputs.targetBranch }}
         title: tag/${{ github.event.inputs.tagVersion }} into ${{ github.event.inputs.targetBranch }}
         reviewers: ${{ github.event.issue.user.login }}
         body: |
           Hi!
           This PR was created in response workflow running.
           I've updated the version and code commit: ${{ steps.make-commit.outputs.commit }}

