# This is a basic workflow that is manually triggered

name: Test version bump workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  create:
    tags:
      -**

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  bump-version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
      - uses: actions/checkout@v2
      
      - name: Set output
        id: vars
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}
          echo ::set-output name=branch::${GITHUB_REF##*/} 
        
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
          echo ${{ steps.vars.outputs.branch }}
          
      - name: Update config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
       
        
      - name: Bump Versions
        # You may pin to the exact commit or the version.
        # uses: remorses/bump-version@bcb347631544a8b9b146bf5de4548376c1f71661
        uses: remorses/bump-version@v8
       
